spring:
  rabbitmq:
    host: 192.168.0.158
    port: 5672
    username: admin
    password: 123456sssdddd
    virtual-host: /
    listener:
      type: direct
      direct:
        acknowledge-mode: manual


















